# Generated by Django 3.0.8 on 2020-10-11 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(blank=True, null=True, verbose_name='size')),
                ('diameter', models.FloatField(blank=True, null=True, verbose_name='diameter')),
                ('shape', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Round'), (1, 'Princess'), (2, 'Cushion'), (3, 'Oval'), (4, 'Emerald'), (5, 'Heart'), (6, 'Pear'), (7, 'Marquise'), (8, 'Asscher'), (9, 'Radiant')], null=True)),
                ('cut', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Poor'), (1, 'Fair'), (2, 'Good'), (3, 'Very Good'), (4, 'Excellent')], null=True)),
                ('symmetry_cut', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Poor'), (1, 'Fair'), (2, 'Good'), (3, 'Very Good'), (4, 'Excellent')], null=True)),
                ('purity', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'FL'), (1, 'IF'), (2, 'VVS1'), (3, 'VVS2'), (4, 'VS1'), (5, 'VS2'), (6, 'SI1'), (7, 'SI2'), (8, 'SI3'), (9, 'I1')], null=True)),
                ('color', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'D'), (1, 'E'), (2, 'F'), (3, 'G'), (4, 'H'), (5, 'I'), (6, 'J'), (7, 'K'), (8, 'L'), (9, 'M'), (10, 'N')], null=True)),
                ('fluorescence', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'None'), (1, 'Faint'), (2, 'Medium'), (3, 'Strong'), (4, 'Very Strong')], null=True)),
            ],
            options={
                'db_table': 'polish',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='polish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='product.Polish'),
        ),
    ]
