# Generated by Django 3.0.8 on 2020-09-12 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='payable price')),
                ('bill', models.TextField(verbose_name='bill calculation')),
                ('razorpay_order_id', models.CharField(max_length=150, null=True, verbose_name='razorpay order id')),
                ('razorpay_order_response', models.TextField(null=True, verbose_name='razorpay order response')),
                ('receipt', models.CharField(max_length=150, null=True, verbose_name='receipt')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Processing'), (2, 'Paid'), (3, 'Cancelled'), (4, 'Failed')], default=0)),
                ('track_order_status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Processing'), (2, 'Shipped'), (3, 'Cancelled'), (4, 'Returned')], default=0)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_order', to='main_admin.Offer')),
                ('order', models.ManyToManyField(related_name='payment_order', to='user.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_order',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_response', models.TextField(verbose_name='razorpay response')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Processing'), (2, 'Paid'), (3, 'Cancelled'), (4, 'Failed')], default=0)),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment', to='payment.PaymentOrder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
