# Generated by Django 3.0.8 on 2020-09-12 12:55

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import main_admin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.PositiveSmallIntegerField(choices=[(0, 'Contact us'), (1, 'Post Requirement')], default=0)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Enter Only Characters or Space')], verbose_name='full name')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.RegexValidator('^\\+??\\d{10,15}$', "Phone number must be entered in the format: '+XX9999999999'.")], verbose_name='contact no')),
                ('country', models.CharField(blank=True, max_length=15, null=True, verbose_name='country')),
                ('subject', models.CharField(max_length=80, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Checked'), (1, 'Not Checked')], default=1)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_type', models.PositiveSmallIntegerField(choices=[(0, 'Return Policy'), (1, 'FAQ')], default=1)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'db_table': 'details',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to=main_admin.models.get_image_path, verbose_name='image')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='coupon code')),
                ('discount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='discount')),
                ('start_time', models.DateTimeField(help_text='offer start time', verbose_name='start time')),
                ('end_time', models.DateTimeField(help_text='end start time', verbose_name='end time')),
                ('minimun_order_price', models.FloatField(blank=True, null=True, verbose_name='minimum order price')),
                ('maximun_discount', models.FloatField(blank=True, null=True, verbose_name='maximum discount')),
                ('offer_type', models.PositiveSmallIntegerField(choices=[(0, 'Flat'), (1, '%')], default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (0, 'Deactive')], default=1)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
            ],
            options={
                'db_table': 'offer',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_icon', models.CharField(default='fas fa-external-link-alt', max_length=50, verbose_name='social icon')),
                ('link', models.TextField(verbose_name='social link')),
            ],
            options={
                'db_table': 'soical_link',
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('main_intro', models.TextField(blank=True, null=True, verbose_name='main intro')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('phone', models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.RegexValidator('^\\+??\\d{10,15}$', "Phone number must be entered in the format: '+XX9999999999'.")], verbose_name='phone')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('logo', models.ImageField(null=True, upload_to=main_admin.models.get_logo_path, verbose_name='logo')),
                ('social_links', models.ManyToManyField(blank=True, related_name='about_us', to='main_admin.SocialLink')),
            ],
            options={
                'db_table': 'about_us',
            },
        ),
    ]
